# Cryptofeed Configuration

# ClickHouse Configuration (时序数据库)
clickhouse:
  host: clickhouse  # Docker服务名，本地开发时使用localhost
  port: 8123
  user: default
  password: password123
  database: cryptofeed
  secure: false

# Symbol selection configuration
symbols:
  mode: "custom"  # Options: "all", "custom", "filter"
  max_contracts: 500  # Maximum number of contracts to monitor
  update_interval: 300  # Check for new/removed symbols every 5 minutes

  # Custom symbol list (used when mode = "custom")
  custom_list:
    - "BTC-USDT-PERP"
    - "ETH-USDT-PERP"
    - "SOL-USDT-PERP"
    - "DOGE-USDT-PERP"
    - "ADA-USDT-PERP"

  # Filtering criteria (used when mode = "filter")
  filters:
    min_24h_volume: 1000000  # Minimum 24h volume in USD
    top_n_by_volume: 100     # Take top N symbols by 24h volume
    exclude_patterns:        # Exclude symbols matching these patterns
      - "*TEST*"
      - "*BULL*"
      - "*BEAR*"
    include_patterns:        # Only include symbols matching these patterns (optional)
      - "*USDT-PERP"

connection_pool:
  streams_per_connection: 1000
  auto_scaling:
    enabled: true
    symbol_check_interval: 300

collection:
  data_types:
    - trades
    - funding
    - candles_1m
    - candles_5m
    - candles_30m
    - candles_4h
    - candles_1d
    - liquidations
    - open_interest

monitoring:
  metrics_enabled: true
  health_check_port: 8080
  stats_interval: 300

logging:
  level: INFO
  filename: logs/cryptofeed_monitor.log

# 数据保留策略配置
data_retention:
  # K线数据保留策略（天数）
  candles:
    "1m": 30      # 1分钟K线：数据量大，保留30天
    "5m": 90      # 5分钟K线：保留90天
    "15m": 180    # 15分钟K线：保留180天
    "30m": 365    # 30分钟K线：保留1年
    "4h": 730     # 4小时K线：保留2年
    "1d": 1095    # 日K线：保留3年

  # 交易数据保留策略（天数）
  trades: 90      # 交易数据保留90天

  # 资金费率保留策略（天数）
  funding: 365    # 资金费率保留1年

  # 清算数据保留策略（天数）
  liquidations: 180  # 清算数据保留180天

  # 持仓量数据保留策略（天数）
  open_interest: 365  # 持仓量保留1年

# 数据完整性检查配置
data_integrity:
  enabled: true              # 启用数据完整性检查
  startup_check: true        # 启动时运行完整性检查
  check_interval_hours: 24   # 定期检查间隔（小时）
  lookback_days: 3           # 检查最近N天的数据
  max_symbols: 10            # 每次检查的最大交易对数量

  # 启用的检查类型
  check_types:
    candles: true
    trades: false    # 交易数据量大，暂时关闭检查
    funding: true
    liquidations: true
    open_interest: true

# 历史数据回填配置
data_backfill:
  enabled: true              # 启用历史数据回填 (设为true启用)
  startup_backfill: true     # 启动时运行一次回填
  continuous_backfill: false # 持续后台回填（慎用，会增加API负载）
  check_interval_hours: 6    # 检查间隔（小时）
  max_concurrent_tasks: 2    # 最大并发回填任务数

  # 回填策略（根据数据保留策略自动计算回填天数）
  # 每个时间间隔使用对应的保留天数作为回填天数
  lookback_by_interval:  # 各时间间隔的回填天数
    "1m": 30      # 1分钟线回填30天
    "5m": 90      # 5分钟线回填90天
    "15m": 180    # 15分钟线回填180天
    "30m": 365    # 30分钟线回填365天
    "4h": 730     # 4小时线回填730天
    "1d": 1095    # 日线回填1095天
  default_lookback_days: 7  # 默认回填天数（兜底值）

  strategy:
    # 不同数据类型的历史数据下载天数
    candles:
      "1m": 7       # 1分钟K线补充最近7天
      "5m": 30      # 5分钟K线补充最近30天
      "15m": 90     # 15分钟K线补充最近90天
      "30m": 180    # 30分钟K线补充最近180天
      "4h": 365     # 4小时K线补充最近1年
      "1d": 730     # 日K线补充最近2年

    trades: 7         # 交易数据补充最近7天（减少负载）
    funding: 90       # 资金费率补充最近90天
    liquidations: 60  # 清算数据补充最近60天
    open_interest: 90 # 持仓量补充最近90天

  # API限制配置
  rate_limits:
    retry_attempts: 3         # 重试次数
    batch_size: 1000         # 每批次处理数量
    request_delay_ms: 200    # 请求间延迟（毫秒）