# Cryptofeed 精简配置 - 统一数据保留策略

# ClickHouse数据库配置
clickhouse:
  host: localhost  # 本地测试使用localhost
  port: 8123
  user: default
  password: password123
  database: cryptofeed
  secure: false

# 交易对配置
symbols:
  mode: "custom"  # 使用自定义交易对列表
  custom_list:
    - "BTC-USDT-PERP"
    - "ETH-USDT-PERP"
    - "SOL-USDT-PERP"
    - "DOGE-USDT-PERP"
    - "ADA-USDT-PERP"

# 数据收集类型
collection:
  data_types:
    - trades
    - funding
    - candles_1m
    - candles_5m
    - candles_30m
    - candles_4h
    - candles_1d
    - liquidations
    - open_interest

# 统一数据保留策略（同时用于TTL、监控检查、历史回填）
data_retention:
  # K线数据保留策略（天数）
  candles:
    "1m": 30      # 1分钟K线：30天
    "5m": 90      # 5分钟K线：90天
    "15m": 180    # 15分钟K线：180天
    "30m": 365    # 30分钟K线：1年
    "4h": 730     # 4小时K线：2年
    "1d": 1095    # 日K线：3年

  # 其他数据保留策略（天数）
  trades: 90           # 交易数据：90天
  funding: 365         # 资金费率：1年
  liquidations: 180    # 清算数据：180天
  open_interest: 365   # 持仓量：1年

# 历史数据回填配置（使用data_retention中的配置）
data_backfill:
  enabled: true              # 启用历史数据回填
  smart_mode: true           # 启用智能回填模式
  startup_backfill: true     # 启动时运行一次回填
  check_interval_hours: 6    # 检查间隔（小时）
  max_concurrent_tasks: 5    # 最大并发回填任务数

  # 智能回填策略
  smart_backfill:
    # 快速检查（只查时间戳，不下载数据）
    quick_check: true
    # 优先级策略
    priority_strategy:
      urgent_threshold_hours: 1     # 紧急缺口阈值（小时）
      recent_threshold_hours: 24    # 近期缺口阈值（小时）
      daily_threshold_days: 7       # 日常缺口阈值（天）
    # 并发控制
    concurrent_pools:
      urgent: 3              # 紧急任务最大并发
      recent: 2              # 近期任务最大并发
      historical: 1          # 历史任务最大并发

  # API限制配置
  rate_limits:
    retry_attempts: 3         # 重试次数
    batch_size: 1500         # 每批次处理数量（Binance官方最大1500）
    request_delay_ms: 50     # 请求间延迟（毫秒）

# 监控配置
monitoring:
  metrics_enabled: true
  health_check_port: 8080
  stats_interval: 300

# 日志配置
logging:
  level: INFO
  filename: logs/cryptofeed_monitor.log